/** Centralized registry for supported user configuration and runner-owned environment keys. */
export const ENV_KEYS = {
  // User-controlled credentials and connection settings
  UMACTUALLY_API_URL: "UMACTUALLY_API_URL",
  UMACTUALLY_API_KEY: "UMACTUALLY_API_KEY",
  UMACTUALLY_MODEL: "UMACTUALLY_MODEL",
  UMACTUALLY_PROVIDER: "UMACTUALLY_PROVIDER",
  UMACTUALLY_GITHUB_API_BASE: "UMACTUALLY_GITHUB_API_BASE",
  // GitHub runner metadata
  GITHUB_ACTIONS: "GITHUB_ACTIONS",
  GITHUB_EVENT_PATH: "GITHUB_EVENT_PATH",
  GITHUB_TOKEN: "GITHUB_TOKEN",
  GH_TOKEN: "GH_TOKEN",
  GITHUB_REPOSITORY: "GITHUB_REPOSITORY",
  GITHUB_REF: "GITHUB_REF",
  GITHUB_SHA: "GITHUB_SHA",
  // Azure DevOps runner metadata
  TF_BUILD: "TF_BUILD",
  SYSTEM_ACCESSTOKEN: "SYSTEM_ACCESSTOKEN",
  SYSTEM_TEAMPROJECT: "SYSTEM_TEAMPROJECT",
  SYSTEM_COLLECTIONURI: "SYSTEM_COLLECTIONURI",
  BUILD_REPOSITORY_ID: "BUILD_REPOSITORY_ID",
  SYSTEM_PULLREQUEST_PULLREQUESTID: "SYSTEM_PULLREQUEST_PULLREQUESTID",
  SYSTEM_PULLREQUEST_SOURCECOMMITID: "SYSTEM_PULLREQUEST_SOURCECOMMITID",
  SYSTEM_PULLREQUEST_TARGETBRANCHNAME: "SYSTEM_PULLREQUEST_TARGETBRANCHNAME",
  // GitHub action inputs
  INPUT_DRY_RUN: "INPUT_DRY_RUN",
  INPUT_EVENT: "INPUT_EVENT",
  INPUT_DIFF: "INPUT_DIFF",
  INPUT_REVIEW: "INPUT_REVIEW",
  INPUT_THREADS: "INPUT_THREADS",
  INPUT_OUTPUT_ARTIFACT: "INPUT_OUTPUT_ARTIFACT",
  INPUT_PLATFORM: "INPUT_PLATFORM",
} as const;
