// Unit tests for the Azure DevOps PR Status POST body sanitization.
//
// Background: Azure DevOps PR Status descriptions are single-line text fields.
// The documented contract at
//   https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-statuses/create?view=azure-devops-rest-7.1
// says only `context.name` is required; `description` is a free-form string
// describing current state. In practice, the live API rejects strings that
// contain the LF character ('\u000A') with HTTP 400:
//
//   "TF20507: The string argument contains a character that is not valid:'u000A'.
//    Correct the argument, and then try the operation again.
//    Parameter name: Description"
//
// This bug surfaced in build #74 (Azure live review run of PR #42) when
// `buildMalformedProviderFallback` (live-shared.ts) returned a multi-line
// `summary` and the orchestrator passed that string verbatim as `description`
// to `postAzureStatus`. `description.slice(0, 255)` does not strip control
// characters, so the LF character made it through to the live API.
//
// The fix is to sanitize the status `description` so it is safe to send to
// the ADO PR Status POST endpoint:
//   1. Strip / replace LF (\u000A) and CR (\u000D) characters.
//   2. Strip other ASCII control characters (TAB excepted) so the field is
//      always a clean single-line description.
//   3. Preserve the documented 255-char upper bound.
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { parseCliArgs } from "../../src/cli.js";
import { runLive } from "../../src/cli/orchestrator.js";
import { azureDiffRoutes, azureReviewDiffFixture } from "./azure-diff-fixture.js";
import type { AzureFetchRoute } from "./azure-diff-fixture.js";

type RecordedCall = {
  readonly url: string;
  readonly method: string;
  readonly authorization: string;
  readonly body: unknown;
};

type FreshableRoute = {
  readonly match: (url: string, method: string) => boolean;
  readonly response: Response | (() => Response);
};

const PROVIDER_REVIEW_MULTILINE_SUMMARY = JSON.stringify({
  // Summary contains literal LF characters: matches what
  // `buildMalformedProviderFallback` produces when the provider returns a
  // non-JSON response (the summary embeds a multi-line `<details>` block).
  summary:
    "Provider response did not contain a valid JSON review payload.\n\n" +
    "<details>\n<summary>📨 Raw provider response (truncated)</summary>\n\n" +
    "```text\nblah\n```\n</details>\n\n" +
    "*Generated by `auto` via `openai-compatible`.*",
  verdict: "COMMENT",
  comments: [
    {
      path: "src/review/example.ts",
      line: 3,
      body: "Azure inline comment.",
      severity: "medium",
      category: "maintainability",
    },
  ],
  suppressed_comments: [],
});

function makeJsonResponse(value: unknown, status = 200): Response {
  return new Response(JSON.stringify(value), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function makeFetchRecorder(routes: readonly FreshableRoute[]): {
  readonly calls: RecordedCall[];
  readonly fetchImpl: typeof fetch;
} {
  const calls: RecordedCall[] = [];
  const fetchImpl: typeof fetch = async (input, init) => {
    const url = typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url;
    const method = init?.method ?? "GET";
    const headers = new Headers(init?.headers);
    const authorization = headers.get("authorization") ?? "";
    const rawBody = init?.body;
    const body = typeof rawBody === "string" ? parseJson(rawBody) : null;
    calls.push({ url, method, authorization, body });
    for (const route of routes) {
      if (route.match(url, method)) {
        return typeof route.response === "function" ? route.response() : route.response;
      }
    }
    throw new Error(`unexpected ${method} ${url}`);
  };
  return { calls, fetchImpl };
}

function parseJson(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch (error) {
    if (error instanceof SyntaxError) {
      return text;
    }
    throw error;
  }
}

function readRecord(value: unknown, label: string): Record<string, unknown> {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  throw new TypeError(`${label} must be an object`);
}

function findCall(calls: readonly RecordedCall[], method: string, urlSuffix: string): RecordedCall {
  for (const call of calls) {
    if (call.method === method && call.url.endsWith(urlSuffix)) {
      return call;
    }
  }
  throw new Error(`missing ${method} ${urlSuffix}`);
}

function freshable(routes: readonly AzureFetchRoute[]): FreshableRoute[] {
  return routes.map((route) => ({
    match: route.match,
    response: () => route.response,
  }));
}

function azureEnv(): NodeJS.ProcessEnv {
  return {
    TF_BUILD: "True",
    SYSTEM_ACCESSTOKEN: "azure-token-secret",
    SYSTEM_COLLECTIONURI: "https://dev.azure.com/example-org/",
    SYSTEM_TEAMPROJECT: "Example Project",
    BUILD_REPOSITORY_ID: "repo-42",
    SYSTEM_PULLREQUEST_PULLREQUESTID: "42",
    SYSTEM_PULLREQUEST_SOURCECOMMITID: "1111111111111111111111111111111111111111",
    SYSTEM_PULLREQUEST_TARGETBRANCHNAME: "refs/heads/main",
    UMACTUALLY_API_URL: "https://provider.example/v1",
    UMACTUALLY_API_KEY: "provider-key-secret",
    UMACTUALLY_MODEL: "review-model-synthetic",
  } satisfies NodeJS.ProcessEnv;
}

describe("postAzureStatus body sanitization", () => {
  let stderrSpy: ReturnType<typeof vi.spyOn> | undefined;

  beforeEach(() => {
    stderrSpy = vi.spyOn(process.stderr, "write").mockImplementation(() => true);
  });

  afterEach(() => {
    stderrSpy?.mockRestore();
    stderrSpy = undefined;
  });

  it("AZURE-STATUS-1: status POST description is sanitized so LF (\u000A) cannot reach the live API", async () => {
    // Given: a live Azure environment whose provider returns a multi-line
    // summary that contains LF characters. This is the exact shape that
    // build #74 of PR #42 hit on the failing live review run.
    let threadPostCount = 0;
    const routes: FreshableRoute[] = [
      ...freshable(azureDiffRoutes(makeJsonResponse, azureReviewDiffFixture())),
      {
        match: (url, method) => method === "POST" && url === "https://provider.example/v1/responses",
        response: () => makeJsonResponse({ output_text: PROVIDER_REVIEW_MULTILINE_SUMMARY }),
      },
      {
        match: (url, method) => method === "GET" && url.endsWith("/threads?api-version=7.1"),
        response: () => makeJsonResponse({ count: 0, value: [] }),
      },
      {
        match: (url, method) => method === "POST" && url.endsWith("/threads?api-version=7.1"),
        response: () => makeJsonResponse({ id: 77 + (threadPostCount += 1) }, 200),
      },
      {
        match: (url, method) => method === "GET" && url.endsWith("/statuses?api-version=7.1"),
        // Empty statuses list: new dedup helper looks here first.
        response: () => makeJsonResponse({ count: 0, value: [] }),
      },
      {
        match: (url, method) => method === "POST" && url.endsWith("/statuses?api-version=7.1"),
        response: () => makeJsonResponse({ id: 88 }, 200),
      },
    ];
    const recorder = makeFetchRecorder(routes);

    // When: the live Azure path runs and the status POST fires.
    const result = await runLive({
      parsed: parseCliArgs(["--platform", "azure", "--no-dry-run"]),
      cwd: process.cwd(),
      env: azureEnv(),
      fetchImpl: recorder.fetchImpl,
    });

    // Then: the run still succeeds (status POST does not blow up).
    expect(result.exitCode).toBe(0);

    // And: the status POST body's `description` field MUST NOT contain an LF
    // character. ADO rejects the field with HTTP 400 TF20507 otherwise.
    const statusPost = findCall(recorder.calls, "POST", "/statuses?api-version=7.1");
    const statusBody = readRecord(statusPost.body as Record<string, unknown>, "status post body");
    const description = statusBody["description"];
    expect(typeof description).toBe("string");
    if (typeof description !== "string") {
      throw new Error("description must be a string");
    }
    expect(description).not.toContain("\n");
    expect(description).not.toContain("\r");
  });

  it("AZURE-STATUS-2: status POST description remains bounded at 255 chars after sanitization", async () => {
    // Given: a provider summary that is already longer than 255 chars and
    // contains an LF embedded inside it. The fix must keep the documented
    // 255-char upper bound while stripping control chars.
    const longSummary = "x".repeat(200) + "\n" + "y".repeat(100);
    const providerJson = JSON.stringify({
      summary: longSummary,
      verdict: "COMMENT",
      comments: [
        {
          path: "src/review/example.ts",
          line: 3,
          body: "Azure inline comment.",
          severity: "medium",
          category: "maintainability",
        },
      ],
      suppressed_comments: [],
    });

    let threadPostCount = 0;
    const routes: FreshableRoute[] = [
      ...freshable(azureDiffRoutes(makeJsonResponse, azureReviewDiffFixture())),
      {
        match: (url, method) => method === "POST" && url === "https://provider.example/v1/responses",
        response: () => makeJsonResponse({ output_text: providerJson }),
      },
      {
        match: (url, method) => method === "GET" && url.endsWith("/threads?api-version=7.1"),
        response: () => makeJsonResponse({ count: 0, value: [] }),
      },
      {
        match: (url, method) => method === "POST" && url.endsWith("/threads?api-version=7.1"),
        response: () => makeJsonResponse({ id: 77 + (threadPostCount += 1) }, 200),
      },
      {
        match: (url, method) => method === "GET" && url.endsWith("/statuses?api-version=7.1"),
        // Empty statuses list: new dedup helper looks here first.
        response: () => makeJsonResponse({ count: 0, value: [] }),
      },
      {
        match: (url, method) => method === "POST" && url.endsWith("/statuses?api-version=7.1"),
        response: () => makeJsonResponse({ id: 88 }, 200),
      },
    ];
    const recorder = makeFetchRecorder(routes);

    await runLive({
      parsed: parseCliArgs(["--platform", "azure", "--no-dry-run"]),
      cwd: process.cwd(),
      env: azureEnv(),
      fetchImpl: recorder.fetchImpl,
    });

    const statusPost = findCall(recorder.calls, "POST", "/statuses?api-version=7.1");
    const statusBody = readRecord(statusPost.body as Record<string, unknown>, "status post body");
    const description = statusBody["description"];
    expect(typeof description).toBe("string");
    if (typeof description !== "string") {
      throw new Error("description must be a string");
    }
    expect(description.length).toBeLessThanOrEqual(255);
    expect(description).not.toContain("\n");
    expect(description).not.toContain("\r");
  });

  it("AZURE-STATUS-3: surfaces the ADO 400 response body on stderr so future failures are debuggable from CI logs", async () => {
    // Given: the live API returns the exact TF20507 body that build #74 hit.
    const tf20507Body = JSON.stringify({
      $id: "1",
      innerException: null,
      message:
        "TF20507: The string argument contains a character that is not valid:'u000A'. " +
        "Correct the argument, and then try the operation again.\r\nParameter name: Description",
      typeName: "System.ArgumentException, mscorlib",
      typeKey: "ArgumentException",
      errorCode: 0,
      eventId: 0,
    });
    let threadPostCount = 0;
    const routes: FreshableRoute[] = [
      ...freshable(azureDiffRoutes(makeJsonResponse, azureReviewDiffFixture())),
      {
        match: (url, method) => method === "POST" && url === "https://provider.example/v1/responses",
        response: () => makeJsonResponse({ output_text: PROVIDER_REVIEW_MULTILINE_SUMMARY }),
      },
      {
        match: (url, method) => method === "GET" && url.endsWith("/threads?api-version=7.1"),
        response: () => makeJsonResponse({ count: 0, value: [] }),
      },
      {
        match: (url, method) => method === "POST" && url.endsWith("/threads?api-version=7.1"),
        response: () => makeJsonResponse({ id: 77 + (threadPostCount += 1) }, 200),
      },
      {
        match: (url, method) => method === "GET" && url.endsWith("/statuses?api-version=7.1"),
        // Empty statuses list: new dedup helper looks here first.
        response: () => makeJsonResponse({ count: 0, value: [] }),
      },
      {
        match: (url, method) => method === "POST" && url.endsWith("/statuses?api-version=7.1"),
        response: () => makeJsonResponse({ message: tf20507Body }, 400),
      },
    ];
    const recorder = makeFetchRecorder(routes);

    // When: the live Azure path runs and the status POST 400s.
    await runLive({
      parsed: parseCliArgs(["--platform", "azure", "--no-dry-run"]),
      cwd: process.cwd(),
      env: azureEnv(),
      fetchImpl: recorder.fetchImpl,
    });

    // Then: stderr captured the ADO error body verbatim (and at error
    // level via the `::error::` prefix so Azure Pipelines shows it).
    expect(stderrSpy).toBeDefined();
    const stderrCalls = (stderrSpy?.mock.calls ?? []).map((args: unknown) =>
      String((args as readonly unknown[])[0] ?? ""),
    );
    const errorLine = stderrCalls.find(
      (line: string) =>
        line.includes("::error::") && line.includes("Azure create PR status HTTP 400"),
    );
    expect(errorLine).toBeDefined();
    expect(errorLine ?? "").toContain("TF20507");
    expect(errorLine ?? "").toContain("u000A");
  });
});